<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.90" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Moq" Version="4.20.70" />
    <PackageVersion Include="NUnit" Version="4.2.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.4.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageVersion Include="Plugin.AdMob" Version="10.0.90" />
    <PackageVersion Include="SkiaSharp" Version="3.119.2" />
    <PackageVersion Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
    <PackageVersion Include="ZXing.Net.Maui" Version="0.10.4" />
    <PackageVersion Include="ZXing.Net.Maui.Controls" Version="0.10.4" />
  </ItemGroup>
</Project>
