using CoreApp.Entities.Shared;
using CoreApp.Interfaces;

namespace CoreApp.Entities.ContainerAggregate;

public class Container : BaseEntity, IAggregateRoot
{
    public Container()
    {
        ContainerId = Guid.NewGuid();
        Name = $"AutoGenerated: {ContainerId}";
        Notes = string.Empty;
        Photos = new List<ImageItem>();
        Items = new List<StoredItem>();
    }

    public Container(Guid containerId, string name, string notes)
    {
        ContainerId = containerId == Guid.Empty ?
            Guid.NewGuid() :
            containerId;

        Name = name;
        Notes = notes;
        Photos = new List<ImageItem>();
        Items = new List<StoredItem>();
    }

    public Guid ContainerId { get; set; }
    public string Name { get; set; }
    public string Notes { get; set; }
    public List<ImageItem> Photos { get; private set; }
    public List<StoredItem> Items { get; private set; }
    public int ItemCount => Items.Sum(i => i.Quantity);

    public void AddItem(Guid itemId, int quantity)
    {
        if (quantity <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(quantity), "Quantity must be greater than zero.");
        }

        var existingItem = Items.Find(i => i.ItemId == itemId);
        if (existingItem != null)
        {
            existingItem.AddQuantity(quantity);
        }
        else
        {
            Items.Add(new StoredItem(itemId, quantity));
        }
    }

    public ImageItem AddImageItem()
    {
        var newImage = new ImageItem();
        Photos.Add(newImage);
        return newImage;
    }

    public void AddImageItem(Guid imageId)
    {
        Photos.Add(new ImageItem(imageId));
    }

    public void RemoveImageItem(Guid imageId)
    {
        Photos.RemoveAll(p => p.ImageId == imageId);
    }

    public void RemoveItem(Guid itemId)
    {
        Items.RemoveAll(i => i.ItemId == itemId);
    }
}
