using CoreApp.Entities.Shared;

namespace CoreApp.Entities.ContainerAggregate;

public class Container : BaseEntity, IAggregateRoot
{
    private readonly List<ImageItem> photos = new();
    private readonly List<StoredItem> items = new();

    public Container()
    {
        ContainerId = Guid.NewGuid();
        Name = $"AutoGenerated: {ContainerId}";
        Notes = string.Empty;
    }

    public Container(Guid containerId, string name, string notes)
    {
        ContainerId = containerId == Guid.Empty ?
            Guid.NewGuid() :
            containerId;

        UpdateDetails(name, notes);
    }

    public Guid ContainerId { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public string Notes { get; private set; } = string.Empty;
    public IReadOnlyList<ImageItem> Photos => photos.AsReadOnly();
    public IReadOnlyList<StoredItem> Items => items.AsReadOnly();
    public int ItemCount => items.Sum(i => i.Quantity);

    /// <summary>
    /// Updates the container's name and notes.
    /// </summary>
    /// <param name="name">The new container name.</param>
    /// <param name="notes">The new container notes.</param>
    public void UpdateDetails(string name, string notes)
    {
        Name = name ?? string.Empty;
        Notes = notes ?? string.Empty;
    }

    /// <summary>
    /// Adds quantity for an item to the container.
    /// </summary>
    /// <param name="itemId">The identifier of the item to add.</param>
    /// <param name="quantity">The positive quantity to add.</param>
    public void AddItem(Guid itemId, int quantity)
    {
        if (quantity <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(quantity), "Quantity must be greater than zero.");
        }

        var existingItem = items.Find(i => i.ItemId == itemId);
        if (existingItem != null)
        {
            existingItem.AddQuantity(quantity);
        }
        else
        {
            items.Add(new StoredItem(itemId, quantity));
        }
    }

    /// <summary>
    /// Creates and adds a new image to the container.
    /// </summary>
    /// <returns>The image added to the container.</returns>
    public ImageItem AddImageItem()
    {
        var newImage = new ImageItem();
        photos.Add(newImage);
        return newImage;
    }

    /// <summary>
    /// Creates and adds an image with the specified identifier to the container.
    /// </summary>
    /// <param name="imageId">The identifier for the image.</param>
    /// <returns>The image added to the container.</returns>
    public ImageItem AddImageItem(Guid imageId)
    {
        var image = new ImageItem(imageId);
        photos.Add(image);
        return image;
    }

    /// <summary>
    /// Adds images to the container.
    /// </summary>
    /// <param name="imageItems">The images to add.</param>
    public void AddImageItems(IEnumerable<ImageItem> imageItems)
    {
        ArgumentNullException.ThrowIfNull(imageItems);
        photos.AddRange(imageItems);
    }

    /// <summary>
    /// Removes an image from the container.
    /// </summary>
    /// <param name="imageId">The identifier of the image to remove.</param>
    public void RemoveImageItem(Guid imageId)
    {
        photos.RemoveAll(p => p.ImageId == imageId);
    }

    /// <summary>
    /// Removes an item and its stored quantity from the container.
    /// </summary>
    /// <param name="itemId">The identifier of the item to remove.</param>
    public void RemoveItem(Guid itemId)
    {
        items.RemoveAll(i => i.ItemId == itemId);
    }
}
