using CoreApp.Entities.Shared;

namespace CoreApp.Entities.ContainerAggregate;

public class Container : BaseEntity, IAggregateRoot
{
    private readonly List<ImageItem> photos = new();
    private readonly List<StoredItem> items = new();

    public Container()
    {
        ContainerId = Guid.NewGuid();
        Name = $"AutoGenerated: {ContainerId}";
        Notes = string.Empty;
    }

    public Container(Guid containerId, string name, string notes)
    {
        ContainerId = containerId == Guid.Empty ?
            Guid.NewGuid() :
            containerId;

        UpdateDetails(name, notes);
    }

    public Guid ContainerId { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public string Notes { get; private set; } = string.Empty;
    public IReadOnlyList<ImageItem> Photos => photos.AsReadOnly();
    public IReadOnlyList<StoredItem> Items => items.AsReadOnly();
    public int ItemCount => items.Sum(i => i.Quantity);

    public void UpdateDetails(string name, string notes)
    {
        Name = name ?? string.Empty;
        Notes = notes ?? string.Empty;
    }

    public void AddItem(Guid itemId, int quantity)
    {
        if (quantity <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(quantity), "Quantity must be greater than zero.");
        }

        var existingItem = items.Find(i => i.ItemId == itemId);
        if (existingItem != null)
        {
            existingItem.AddQuantity(quantity);
        }
        else
        {
            items.Add(new StoredItem(itemId, quantity));
        }
    }

    public ImageItem AddImageItem()
    {
        var newImage = new ImageItem();
        photos.Add(newImage);
        return newImage;
    }

    public ImageItem AddImageItem(Guid imageId)
    {
        var image = new ImageItem(imageId);
        photos.Add(image);
        return image;
    }

    public void AddImageItems(IEnumerable<ImageItem> imageItems)
    {
        ArgumentNullException.ThrowIfNull(imageItems);
        photos.AddRange(imageItems);
    }

    public void RemoveImageItem(Guid imageId)
    {
        photos.RemoveAll(p => p.ImageId == imageId);
    }

    public void RemoveItem(Guid itemId)
    {
        items.RemoveAll(i => i.ItemId == itemId);
    }
}
