using CoreApp.Domain.Abstractions;
using CoreApp.Domain.Events;
using CoreApp.Domain.ValueObjects;

namespace CoreApp.Domain.Entities.ItemAggregate;

public class Item : BaseEntity, IAggregateRoot
{
    private readonly List<ImageItem> photos = new();

    public Item()
        : this(Guid.NewGuid())
    {
    }

    public Item(string name, string description)
        : this(Guid.NewGuid(), name, description)
    {
    }

    public Item(Guid itemId, string name, string description)
    {
        if (itemId == Guid.Empty)
        {
            throw new ArgumentException("Item ID cannot be empty.", nameof(itemId));
        }

        ItemId = itemId;
        SetDetailsWithoutEvent(name, description);
        AddDomainEvent(new ItemCreated(ItemId, Name));
    }

    private Item(Guid itemId)
    {
        ItemId = itemId;
        Name = $"AutoGenerated: {ItemId}";
        Description = string.Empty;
    }

    public Guid ItemId { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public string Description { get; private set; } = string.Empty;
    public Barcode? Barcode { get; private set; }
    public IReadOnlyList<ImageItem> Photos => photos.AsReadOnly();

    /// <summary>
    /// Updates the item's name and description.
    /// </summary>
    /// <param name="name">The new item name.</param>
    /// <param name="description">The new item description.</param>
    public void UpdateDetails(string name, string description)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Item name cannot be empty.", nameof(name));
        }

        var normalizedDescription = description ?? string.Empty;
        if (Name == name && Description == normalizedDescription)
        {
            return;
        }

        var previousName = Name;
        var previousDescription = Description;
        Name = name;
        Description = normalizedDescription;
        AddDomainEvent(new ItemDetailsUpdated(ItemId, previousName, Name, previousDescription, Description));
    }

    public void UpdateBarcode(Barcode? barcode)
    {
        if (Barcode == barcode)
        {
            return;
        }

        var previousBarcode = Barcode?.Value;
        Barcode = barcode;
        AddDomainEvent(new ItemBarcodeChanged(ItemId, previousBarcode, Barcode?.Value));
    }

    /// <summary>
    /// Creates and adds a new image to the item.
    /// </summary>
    /// <returns>The image added to the item.</returns>
    public ImageItem AddImageItem()
    {
        var newImage = new ImageItem();
        photos.Add(newImage);
        AddDomainEvent(new ItemPhotoAdded(ItemId, newImage.ImageId, newImage.FileName));

        return newImage;
    }

    /// <summary>
    /// Creates and adds an image with the specified identifier to the item.
    /// </summary>
    /// <param name="imageId">The identifier for the image.</param>
    /// <returns>The image added to the item.</returns>
    public ImageItem AddImageItem(Guid imageId)
    {
        var image = new ImageItem(imageId);
        photos.Add(image);
        AddDomainEvent(new ItemPhotoAdded(ItemId, image.ImageId, image.FileName));

        return image;
    }

    /// <summary>
    /// Adds images to the item.
    /// </summary>
    /// <param name="imageItems">The images to add.</param>
    public void AddImageItems(IEnumerable<ImageItem> imageItems)
    {
        ArgumentNullException.ThrowIfNull(imageItems);
        photos.AddRange(imageItems);
    }

    /// <summary>
    /// Removes an image from the item.
    /// </summary>
    /// <param name="imageId">The identifier of the image to remove.</param>
    public void RemoveImageItem(Guid imageId)
    {
        var removed = photos.Where(photo => photo.ImageId == imageId).ToArray();
        if (removed.Length == 0)
        {
            return;
        }

        photos.RemoveAll(photo => photo.ImageId == imageId);
        foreach (var image in removed)
        {
            AddDomainEvent(new ItemPhotoRemoved(ItemId, image.ImageId, image.FileName));
        }
    }

    private void SetDetailsWithoutEvent(string name, string description)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Item name cannot be empty.", nameof(name));
        }

        Name = name;
        Description = description ?? string.Empty;
    }
}
