using CoreApp.Domain.Abstractions;
using CoreApp.Domain.Entities.Shared;

namespace CoreApp.Domain.Entities.ContainerAggregate;

public class Container : BaseEntity, IAggregateRoot
{
    private readonly List<ImageItem> photos = new();

    public Container()
    {
        ContainerId = Guid.NewGuid();
        Name = $"AutoGenerated: {ContainerId}";
        Notes = string.Empty;
    }

    public Container(Guid containerId, string name, string notes)
    {
        if (containerId == Guid.Empty)
        {
            throw new ArgumentException("Container ID cannot be empty.", nameof(containerId));
        }

        ContainerId = containerId;
        UpdateDetails(name, notes);
    }

    public Guid ContainerId { get; private set; }
    public string Name { get; private set; } = string.Empty;
    public string Notes { get; private set; } = string.Empty;
    public IReadOnlyList<ImageItem> Photos => photos.AsReadOnly();

    // Read-only counts sourced from the ItemInventory aggregate; not owned or persisted by Container itself.
    public int ItemTypeCount { get; private set; }
    public int TotalItemQuantity { get; private set; }

    /// <summary>
    /// Hydrates the item allocation summary for display, sourced from ItemInventory allocations.
    /// </summary>
    /// <param name="itemTypeCount">The number of distinct item types allocated to this container.</param>
    /// <param name="totalItemQuantity">The total allocated item quantity in this container.</param>
    public void SetItemSummary(int itemTypeCount, int totalItemQuantity)
    {
        if (itemTypeCount < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(itemTypeCount), "Item type count cannot be negative.");
        }

        if (totalItemQuantity < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(totalItemQuantity), "Total item quantity cannot be negative.");
        }

        ItemTypeCount = itemTypeCount;
        TotalItemQuantity = totalItemQuantity;
    }

    /// <summary>
    /// Updates the container's name and notes.
    /// </summary>
    /// <param name="name">The new container name.</param>
    /// <param name="notes">The new container notes.</param>
    public void UpdateDetails(string name, string notes)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Container name cannot be empty.", nameof(name));
        }

        Name = name;
        Notes = notes ?? string.Empty;
    }

    /// <summary>
    /// Creates and adds a new image to the container.
    /// </summary>
    /// <returns>The image added to the container.</returns>
    public ImageItem AddImageItem()
    {
        var newImage = new ImageItem();
        photos.Add(newImage);
        return newImage;
    }

    /// <summary>
    /// Creates and adds an image with the specified identifier to the container.
    /// </summary>
    /// <param name="imageId">The identifier for the image.</param>
    /// <returns>The image added to the container.</returns>
    public ImageItem AddImageItem(Guid imageId)
    {
        var image = new ImageItem(imageId);
        photos.Add(image);
        return image;
    }

    /// <summary>
    /// Adds images to the container.
    /// </summary>
    /// <param name="imageItems">The images to add.</param>
    public void AddImageItems(IEnumerable<ImageItem> imageItems)
    {
        ArgumentNullException.ThrowIfNull(imageItems);
        photos.AddRange(imageItems);
    }

    /// <summary>
    /// Removes an image from the container.
    /// </summary>
    /// <param name="imageId">The identifier of the image to remove.</param>
    public void RemoveImageItem(Guid imageId)
    {
        photos.RemoveAll(p => p.ImageId == imageId);
    }
}
